version: '2'
services:
    nginx:
        depends_on:
            - php-fpm
            - db
            - pma
            - redis
        image: nginx
        restart: always
        volumes:
            - ./html:/etc/nginx/html:rw
            - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./conf/conf.d:/etc/nginx/conf.d/:rw
        ports:
            - 80:80
        container_name: nginx
    php-fpm:
        image: php:7.2-fpm
        restart: always
        links:
            - db:db
        volumes:
            - ./html:/etc/nginx/html:rw
            - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
        expose:
        - 9000
        ports:
            - 9000:9000
        container_name: php-fpm
    db:
        image: mysql:5.7
        restart: always
        expose:
        - 33060
        ports:
            - 33060:3306
        volumes:
           - ./mysql/data:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=root
    pma:
        image: phpmyadmin/phpmyadmin
        restart: always
        depends_on:
        - db
        links:
        - db
        ports:
        - 8080:80
        environment:
        - PMA_HOST=db
        - PMA_PORTS=3306
        - PMA_ARBITRARY=1
        - PMA_USER=root
        - PMA_PASSWORD=root
        - VIRTUAL_HOST=localhost
        - LETSENCRYPT_HOST=localhost
        - LETSENCRYPT_EMAIL=494248656@qq.com
    redis:
        image: redis:5.0.3-alpine
        ports:
          - 6378:6379
        volumes:
          - ./conf/redis.conf:/etc/redis.conf:ro
        restart: always
        entrypoint: ["redis-server", "/etc/redis.conf"]
        networks:
          - default